### ISSUE TITLE
Rename to orml-xcm-builder

### ISSUE THREAD

**Issue by arrudagates** [open-web3-stack/orml-xcm-builder#1]
I believe `orml-xcm` would be too vague, and since it also conflicts with the orml-xcm pallet, we should come up with a better name for this library. Perhaps something along the lines of `orml-xcm-configs` or `orml-xcm-builder`?

**Comment by arrudagates** [comment]
Getting back to this, I strongly believe `orml-xcm-builder` is the best name for this crate, as it is quite literally the open version of parity's `xcm-builder` crate.

**Comment by xlc** [comment]
renamed
